name: Terraform Apply
on: workflow_dispatch ##quando ter치 trigger no workflow ##push: toda vez que tiver push ser치 iniciado
env: 
  AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
  AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
  TF_VAR_aws_pub_key: ${{secrets.AWS_PUBLIC_KEY}}

jobs:
  terraform:
    name: terraform
    runs-on: ubuntu-latest ##j치 possui terraform e outras tools instalados
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout ##obrigat칩rio, faz download dos arquivos pra dentro da pipeline
      uses: actions/checkout@v2

    - name: Terraform Init
      run: terraform init

##    - name: Terraform Apply
##      run: terraform apply -auto-approve ##ncessario colocar para nao dar trigger manual